GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiVTJGc2RHVmtYMS9McHg4c29NYkRZeWxSRW5ZazZUaE9OSFFtM21NZjkvakJ4UXd3L0NYS2E0WkN1UW05L2pMeCIsImlhdCI6MTY4ODgwODY0OSwiZXhwIjoxNjg5NDEzNDQ5fQ.jr8ACXH1LGCmXCIMbmJYPic0cNrfU40zy2RTnf3I-0M

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "test@test.com",
    "password": "password1",
    "apartment": 482,
    "name": "Matt Garrow"}