GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiVTJGc2RHVmtYMThKdGtXQzVVZkF3WjBLd05VT08xbGc3b3d3L2dQejZkcHFzQ1FXR1Z2dUNzSDdseitmR2kybyIsImlhdCI6MTY4ODk2NzEwNSwiZXhwIjoxNjg5NTcxOTA1fQ.X8wIlfdb38H7AnbUkAZCEINYCUXc5h34t8AuVirxD2M

###

PUT http://localhost:3001/users/64ab9792f91aa1629e60748a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiVTJGc2RHVmtYMThKdGtXQzVVZkF3WjBLd05VT08xbGc3b3d3L2dQejZkcHFzQ1FXR1Z2dUNzSDdseitmR2kybyIsImlhdCI6MTY4ODk2NzEwNSwiZXhwIjoxNjg5NTcxOTA1fQ.X8wIlfdb38H7AnbUkAZCEINYCUXc5h34t8AuVirxD2M

{
    "username": "newtest@test.com",
    "password": "newpassword1",
    "name": "Matt Barrow"
}